### ISSUE TITLE
Error - "ReflectionException: Class  does not exist"

### ISSUE THREAD

**Issue by sumanchalki** [ricardoamaro/drupal8-docker-app#11]
I am getting error with following output -

**** MySQL data found on /var/lib/mysql/ ****
**** /var/www/html/web/index.php found  ****
grep: /var/www/html/web/sites/default/settings.php: No such file or directory
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
ReflectionException: Class  does not exist in                        [error]
/var/www/html/web/core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php:156

**Comment by rwaesely** [comment]
same here... is the project still active ?

**Comment by fredysan** [comment]
Same here

**Comment by ElMudo** [comment]
I'm also getting the same. There seems to be something wrong with the settings file or with the (Drupal) code base. I would expect the former. I'm totally new to Drupal so I don't know how it should have been specified in the settings file, but if you change line 153 of the file where the error occurs to:
`  $driver = 'mysql';`
and re-run the `start.sh`, then you can at least see that something works. (This is obviously not a solution - but I wanted to just see Drupal running - that was the whole point of this Docker app.)

**Comment by ricardoamaro** [comment]
I changed the driver to mysql and it fixed this problem. Thank you all.
