### ISSUE TITLE
Drush is missing

### ISSUE THREAD

**Issue by kazlauskis** [ricardoamaro/drupal8-docker-app#19]
For some reason the image didn't build for me correctly as it couldn't find drush. Linking it from a different place helped to fix it (line 38) change:
 ` && ln -s /.composer/vendor/drush/drush/drush /usr/local/bin/drush \`
to 
`  && ln -s /.config/composer/vendor/drush/drush/drush /usr/local/bin/drush \`

**Comment by CyberHacky** [comment]
Thanks, Man, 
It's working now, I faced the same issue

**Comment by ricardoamaro** [comment]
Fixed in commit 804f61430cee0e4bfa3dff5ed761ee7ee93e867d
Thank you
