### ISSUE TITLE
Upgrade to Ubuntu 16/04 and use php7.0

### ISSUE THREAD

**Issue by martinfrances107** [ricardoamaro/drupal8-docker-app#2]
I hope this project is still active ... here is my idea.

Ubuntu 16.04 LTS (Xenial) is a Long Term Support release - so it would be a good idea to upgrade.
Drupal 8.x gets a good speedup from php7 - and a massive reduction in memory consumption.

Here are my changes so far

1) Change the image:
-FROM ubuntu:trusty
+FROM ubuntu:xenial

2) Change php packages to php7 equivalent :

```
-  mysql-client mysql-server apache2 libapache2-mod-php5 pwgen \
-  vim-tiny mc python-setuptools unison memcached php5-memcache \
-  php5-cli php5-mysql php-apc php5-gd php5-curl php5-xdebug; \
+  mysql-client mysql-server apache2 libapache2-mod-php7.0 pwgen \
+  vim-tiny mc python-setuptools unison memcached php-memcache \
+  php7.0-cli php7.0-mysql php7.0-opcache php7.0-fpm php7.0-gd php7.0-curl php-xdebug; \
```

php-apc is dropped php-opcache is picked up.

I am posting early while I get this going .... please stop me if you think the direction of the issue is wrong!

**Comment by ricardoamaro** [comment]
Hello @martinfrances107, thanks for the changes. I'll try to review them today. :)

**Comment by andypost** [comment]
I think better to keep php7 in separate branch/directory

**Comment by dminca** [comment]
if you're moving to `php7` it requires `ssh2` to download Modules/Themes from the Admin UI. I've checked whether `ssh2` can be compiled from source for php7 and it's still `alpha`. That's what I'm [currently][1] struggling with now. Just giving you a heads-up

[1]: https://github.com/dminca/drupal-docker/issues/45

**Comment by ricardoamaro** [comment]
Thanks for the good discussion here, @martinfrances107, @andypost , @dminca 
Given that Trusty is going to be supported until 2019 https://wiki.ubuntu.com/LTS and we need to have all the features stable I propose we maintain the current version and review by the end of 2016 to see if all the things are in place for a stable migration to xenial.

**Comment by andypost** [comment]
@ricardoamaro Makes sense, Xenial still has issues

OTOH base image depends on usage of container, for sprints I suggest to use alpine - it allows to have less overhead when running multiple instances and faster download
For that reason I build https://github.com/skilld-labs/docker-php and updated mostly all php7 extensions in alpine testing

**Comment by ricardoamaro** [comment]
I updated today to Bionic 18.04 with PHP 7.2
