### ISSUE TITLE
Container shows drush not found failing drupal installation

### ISSUE THREAD

**Issue by mkd63** [ricardoamaro/drupal8-docker-app#20]
The docker image installs Drush, composer, and drupal perfectly after making changes suggested by @kazlauskis. But, while starting the same in the container. It doesn't install the site on drupal. 
It also throws an error that `/.composer/vendor/drush/drush/drush` does not exist. While it clearly installs drush which is evident from image build logs. It installs drush globally.

@ricardoamaro Please have a look at this issue.

**Comment by mkd63** [comment]
changing 
`export DRUSH="/.composer/vendor/drush/drush/drush"`
to
`export DRUSH="drush"`
worked for me !

**Comment by ricardoamaro** [comment]
Fixed in commit 804f61430cee0e4bfa3dff5ed761ee7ee93e867d
Thank you
