### ISSUE TITLE
Initial Database

### ISSUE THREAD

**Issue by RalfEisler** [ricardoamaro/drupal8-docker-app#7]
Hi,

I am trying to install Drupal with the drupal8-docker-app. One thing is unclear for me: While user/pass is admin/admin, what is the name of the initial database?

And: What are the the username and password for Adminer?

**Comment by Dshosev** [comment]
> Hi,
> 
> I am trying to install Drupal with the drupal8-docker-app. One thing is unclear for me: While user/pass is admin/admin, what is the name of the initial database?
> 
> And: What are the the username and password for Adminer?

I also wanted to try this thing but at the moment i can't connect a database or get into mysql to create one

**Comment by ricardoamaro** [comment]
The initial database is called 'drupal'
